### Use the following code for the questions below:

In [1]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#### 1. How many negative numbers are there?


In [2]:
len(a[a < 0])

4

#### 2. How many positive numbers are there?


In [3]:
len(a[a > 0])

5

In [5]:
# 3. How many even positive numbers are there?


In [6]:
len(a[(a > 0) & (a % 2 == 0)])

3

#### 4. If you were to add 3 to each data point, how many positive numbers would there be?


In [8]:
len(a[(a + 3) > 0])

10

#### 5. If you squared each number, what would the new mean and standard deviation be?


In [10]:
(a ** 2).std()

144.0243035046516

In [12]:
(a ** 2).mean()

74.0

#### 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. 


In [15]:
a_centered = (a - a.mean())
a_centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

#### 7. Calculate the z-score for each data point. Recall that the z-score is given by: Z = (x-mu)/sigma


In [17]:
z_scores = (a - a.mean()) / a.std()
z_scores

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

#### 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.



In [18]:
# Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### Use python's built in functionality/operators to determine the following:

#### Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list


In [21]:
a = np.array(a)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
sum_of_a = a.sum()
sum_of_a

55

#### Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list


In [25]:
min_of_a = a.min()
min_of_a

1

#### Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list


In [26]:
max_of_a = a.max()
max_of_a

10

#### Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


In [28]:
mean_of_a = a.mean()
mean_of_a

5.5

#### Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together


In [30]:
product_of_a = a.prod()
print(a.cumprod())
product_of_a

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


3628800

#### Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]


In [31]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers


In [32]:
odds_in_a = a[a % 2 == 1]
odds_in_a

array([1, 3, 5, 7, 9])

#### Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.


In [33]:
evens_in_a = a[a % 2 == 0]
evens_in_a

array([ 2,  4,  6,  8, 10])

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
### Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.


In [34]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]


#### Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**


In [36]:
b = np.array(b)

#### Exercise 2 - refactor the following to use numpy. 
  

In [39]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)
sum_of_b

33

In [40]:
b.sum()

33

#### Exercise 3 - refactor the following maximum calculation to find the answer with numpy.


In [42]:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1]) 
min_of_b

3

In [43]:
b.min()

3

#### Exercise 4 - refactor the following using numpy to find the mean of b


In [44]:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b

5.5

In [45]:
b.mean()

5.5

#### Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.


In [46]:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

In [47]:
b.prod()

20160

#### Exercise 6 - refactor the following to use numpy to find the list of squares 



In [51]:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [53]:
b ** 2

array([[ 9, 16, 25],
       [36, 49, 64]])

#### Exercise 7 - refactor using numpy to determine the odds_in_b


In [56]:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
odds_in_b

[3, 5, 7]

In [55]:
b[b%2 != 0]

array([3, 5, 7])

#### Exercise 8 - refactor the following to use numpy to filter only the even numbers


In [57]:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
evens_in_b

[4, 6, 8]

In [58]:
b[b % 2 == 0]

array([4, 6, 8])

#### Exercise 9 - print out the shape of the array b.


In [59]:
b.shape

(2, 3)

#### Exercise 10 - transpose the array b.



In [60]:
b.T

array([[3, 6],
       [4, 7],
       [5, 8]])

#### Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)


In [61]:
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [62]:
b

array([[3, 4, 5],
       [6, 7, 8]])

#### Exercise 12 - reshape the array b to be a list of 6 lists,  each containing only 1 number (6 x 1)



In [63]:
b.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Setup 3


In [64]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

#### HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods. Exercise 1 - Find the min, max, sum, and product of c.


In [65]:
c = np.array(c)

In [66]:
c.min()

1

In [67]:
c.max()

9

In [68]:
c.sum()

45

In [69]:
c.prod()

362880

#### Exercise 2 - Determine the standard deviation of c.


In [70]:
c.std()

2.581988897471611

#### Exercise 3 - Determine the variance of c.



In [71]:
c.var()

6.666666666666667

#### Exercise 4 - Print out the shape of the array c


In [72]:
c.shape

(3, 3)

#### Exercise 5 - Transpose c and print out transposed result.


In [73]:
c.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### Exercise 6 - Get the dot product of the array c with c. 


In [74]:
c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

#### Exercise 7 - Write the code necessary to sum up the result of c times c transposed.  Answer should be 261


In [78]:
(c * (c.T)).sum()

261

#### Exercise 8 - Write the code necessary to determine the product of c times c transposed.  Answer should be 131681894400.


In [79]:
(c * c.T).prod()

131681894400

### Setup 4


In [80]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]
d = np.array(d)

#### Exercise 1 - Find the sine of all the numbers in d


In [81]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

#### Exercise 2 - Find the cosine of all the numbers in d


In [82]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

#### Exercise 3 - Find the tangent of all the numbers in d


In [83]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

#### Exercise 4 - Find all the negative numbers in d


In [84]:
d [d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

#### Exercise 5 - Find all the positive numbers in d


In [85]:
d [d < 0]

array([-90, -30, -45, -45])

#### Exercise 6 - Return an array of only the unique numbers in d.


In [89]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

#### Exercise 7 - Determine how many unique numbers there are in d.


In [87]:
len(np.unique(d))

11

#### Exercise 8 - Print out the shape of d.


In [90]:
d.shape

(3, 6)

#### Exercise 9 - Transpose and then print out the shape of d.


In [91]:
print(d.T)

[[ 90  45  60]
 [ 30 -90  45]
 [ 45 -30 -45]
 [  0 270  90]
 [120  90 -45]
 [180   0 180]]


In [93]:
d.T

array([[ 90,  45,  60],
       [ 30, -90,  45],
       [ 45, -30, -45],
       [  0, 270,  90],
       [120,  90, -45],
       [180,   0, 180]])

#### Exercise 10 - Reshape d into an array of 9 x 2

In [94]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [202]:
print(d.reshape(9, 2))

[[ 90  30]
 [ 45   0]
 [120 180]
 [ 45 -90]
 [-30 270]
 [ 90   0]
 [ 60  45]
 [-45  90]
 [-45 180]]
