# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [1]:
#create a list
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [2]:
#whats the type
type(my_list)

list

In [459]:
#what is dtype
#my_list.dtype breaks with list

In [460]:
#whats the shape
#my_list.shape breaks with list

#### create an array
format: np.array()

In [4]:
#import numpy
import numpy as np

In [5]:
#create the array
my_array = np.array(my_list)

In [6]:
#whats the type
type(my_array)

numpy.ndarray

In [9]:
#whats the shape
my_array.shape

(4,)

In [10]:
#dtype
my_array.dtype

dtype('int64')

#### access elements of our new array

In [11]:
my_array

array([1, 2, 3, 4])

In [12]:
my_array[0] #calls the first element of array

1

In [13]:
my_array[-1] #calls the last element of our array

4

#### slice the array

In [ ]:
my_array[1:] #the first element you call is included

In [ ]:
my_array[:3] #second element you call is NOT included

#### create an array from 1 to 100

In [15]:
#np.array(?)
a = np.array(range(1, 101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [16]:
#access single element
a[-1]

100

In [17]:
#slice the array! 
a[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Create a 2D array

In [18]:
#build a list of lists
matrix = [[1,2,3],[2,3,4],[6,7,8]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8]]

In [19]:
type(matrix)

list

In [21]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [23]:
#type
type(matrix_array)

numpy.ndarray

#### access elements

In [25]:
matrix_array[0]  

array([1, 2, 3])

In [26]:
matrix_array[0][0] #alternative to following cell syntax

1

In [27]:
matrix_array[0,0]  #alternative to previous cell syntax

1

### Descriptive Stats

In [28]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### using methods: the method is called on the numpy object

In [30]:
a.max()

100

In [31]:
a.std()

28.86607004772212

#### using functions: using numpy to call functions

In [213]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [32]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [34]:
#combine them 


array([1, 4])

#### how else can we get our array of boolean values?

In [40]:
#write a conditional with the array
my_array == 4 #parens visually useful, not required


array([False, False, False,  True])

#### make and apply our boolean mask

In [35]:
#make list of booleans aka our mask
mask = [True, False, False, True]

In [36]:
#format: array_name [ list_of_booleans ]
my_array[mask]

array([1, 4])

In [39]:
mask = my_array > 2 #parens not required on right side
mask

array([False, False,  True,  True])

#### cool! can we just do it with a list instead of an array?

In [41]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [42]:
#create a array of booleans
my_list == 4

False

In [488]:
#apply an array of booleans to a list


#### let's bring it back to arrays and make them bigger

In [489]:
#array


In [490]:
#mask


In [491]:
#boolean mask


#### shortcut?

#### what if we wanted to check two conditions?

In [492]:
# note the parenthesis
# also note that we're using & instead of and


#### what if we wanted the opposite of our mask?

In [493]:
# the ~ notates the opposite of


## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [494]:
#using a for loop


In [495]:
#using a list comprehension


#### easy way: doing it with an array

In [496]:
#using vectorization operations


### more operations

### show us the speed

In [501]:
#make a really big array


In [502]:
# %%timeit


In [503]:
#make a really big list


In [504]:
# %%timeit


## Numpy ways to create arrays

#### full of zeros

#### full of ones

#### full of whatever you want 

#### a quicker way to make a range

#### an array of random integers

In [506]:
#np.random.randint()


#### an array of random numbers from the standard distribution

In [508]:
#np.random.randn()
