# Advanced Dataframes

## Part 1 - Creating Dataframes

format: `pd.DataFrame(data)`

- from lists
- from dictionaries
- from sql

In [1]:
#imports
import pandas as pd
import numpy as np
import matplotlib as plt


### From lists

In [11]:
#build a matrix (list of lists)
matrix = [[1,2,3],[2,3,55],[6,7,8]]
type(matrix)

list

In [4]:
#pd.DataFrame(data)
pd.DataFrame(matrix)

0  1   2
0  1  2   3
1  2  3  55
2  6  7   8

> note: column names default to integers

In [7]:
#define column names
column_names = ['first','second','third']


> note: the number of column names that i create should match the number of columns I actually have

In [8]:
#pd.DataFrame(data)
pd.DataFrame(matrix, columns=column_names)

first  second  third
0      1       2      3
1      2       3     55
2      6       7      8

In [9]:
#make the matrix an array
matrix_array = np.array(matrix)
matrix_array

array([[ 1,  2,  3],
       [ 2,  3, 55],
       [ 6,  7,  8]])

In [10]:
#pd.DataFrame(data)
pd.DataFrame(matrix_array, columns=column_names)

first  second  third
0      1       2      3
1      2       3     55
2      6       7      8

### From dictionaries

In [12]:
#create a dictionary with a list as keys
new_dt = {'A':[1,3,4], 'B':[2,355,5]}
new_dt

{'A': [1, 3, 4], 'B': [2, 355, 5]}

In [13]:
#create!
pd.DataFrame(new_dt)

A    B
0  1    2
1  3  355
2  4    5

#### make it more complex

In [14]:
np.random.seed(123)

In [15]:
# Create list of values for names column
students = ['Sally', 'Jane', 'Suzie', 'Billy', 'Ada', 'John', 'Thomas',
            'Marie', 'Albert', 'Richard', 'Isaac', 'Alan']

In [16]:
# Randomly generate arrays of scores for each student for each subject.
# Note that all the values need to have the same length here.
math_grades = np.random.randint(low=60, high=100, size=len(students))
english_grades = np.random.randint(low=60, high=100, size=len(students))
reading_grades = np.random.randint(low=60, high=100, size=len(students))

In [20]:
math_grades

array([62, 88, 94, 98, 77, 79, 82, 93, 92, 69, 92, 92])

In [21]:
english_grades

array([85, 79, 74, 96, 92, 76, 64, 63, 62, 80, 99, 62])

In [22]:
reading_grades

array([80, 67, 95, 88, 98, 93, 81, 90, 87, 94, 93, 72])

In [ ]:
# Randomly generate if a student is in classroom A or classroom B
classroom = np.random.choice(['A', 'B'], len(students))

In [25]:
classroom = np.random.choice(['A', 'B'], len(students))

In [26]:
classroom

array(['A', 'B', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'A'],
      dtype='<U1')

In [27]:
#combine all values into a dictionary
student_dict = {
    'students': students,
    'math': math_grades,
    'english': english_grades,
    'reading': reading_grades,
    'room': classroom
}
student_dict

{'students': ['Sally',
  'Jane',
  'Suzie',
  'Billy',
  'Ada',
  'John',
  'Thomas',
  'Marie',
  'Albert',
  'Richard',
  'Isaac',
  'Alan'],
 'math': array([62, 88, 94, 98, 77, 79, 82, 93, 92, 69, 92, 92]),
 'english': array([85, 79, 74, 96, 92, 76, 64, 63, 62, 80, 99, 62]),
 'reading': array([80, 67, 95, 88, 98, 93, 81, 90, 87, 94, 93, 72]),
 'room': array(['A', 'B', 'B', 'A', 'B', 'B', 'B', 'A', 'B', 'B', 'B', 'A'],
       dtype='<U1')}

In [28]:
pd.DataFrame(student_dict)

students  math  english  reading room
0     Sally    62       85       80    A
1      Jane    88       79       67    B
2     Suzie    94       74       95    B
3     Billy    98       96       88    A
4       Ada    77       92       98    B
5      John    79       76       93    B
6    Thomas    82       64       81    B
7     Marie    93       63       90    A
8    Albert    92       62       87    B
9   Richard    69       80       94    B
10    Isaac    92       99       93    B
11     Alan    92       62       72    A

### From SQL

We can connect to sql to create a dataframe!! yay!

To do this we will use a driver to connect the database to our python code using pymysql driver packages

`python -m pip install pymysql`

Now that this is installed, we will create a **CONNECTION STRING**

This is a what a **CONNECTION STRING** looks like: 

`[protocol]://[user]:[password]@[host]/[database_name]`

example of the **CONNECTION STRING**:

`mysql+pymysql://codeup:p@assw0rd@123.123.123.123/some_db`

In this example:

- protocol = 'mysql+pymysql'
- user = 'codeup'
- password = 'p@assw0rd'
- host = '123.123.123.123'
- database_name = 'some_db'

You will each make a unique **CONNECTION STRING** with your credentials

In [ ]:
#example
url = 'mysql+pymysql://codeup:p@assw0rd@123.123.123.123/some_db'

<div class="alert alert-block alert-warning">
    Should you type your username and password in your .py or .ipynb? Why or why not?
</div>

answer: 

<!-- <div class="alert alert-block alert-danger">
    NO! 
</div> -->

How to avoid this? 

1. Create a separate file called env.py
2. Enter in your credentials
3. Put your env.py in the same folder as your working file
4. Import your env
5. Create your connection string from imported variables

<div class="alert alert-block alert-warning">
    Should you push your env.py file to github?
</div>

answer: 

<!-- <div class="alert alert-block alert-danger">
     NO! 
</div> -->

**We will not push our username and password to github**

**We will add our env file to our gitignore**

**We will not rely on our global gitignore to ignore our env file**

**We will add env.py to our gitignore in every repository that we use our env credentials**

In [30]:
import env

ModuleNotFoundError: No module named 'env'

In [29]:
#pull in the hostname
#env.host

NameError: name 'env' is not defined

In [ ]:
#pull in the username
#env.user

In [ ]:
#pull in the password
#env.password

<div class="alert alert-block alert-warning">
    Should you leave your username and password printed out on your .ipynb?
</div>

answer: NO!

<!-- <div class="alert alert-block alert-danger">
    NO! 
</div> -->

lets create our **CONNECTION STRING** saved into a variable called url

In [ ]:
#create connection string
url = f'mysql+pymysql://{env.user}:{env.password}@{env.host}/some_db'

In [ ]:
# url

<div class="alert alert-block alert-warning">
    Should you print out on your connection string?
</div>

answer:

<!-- <div class="alert alert-block alert-danger">
    NO! 
</div> -->

**We will not type our username and password in our working file**

**We will not print out our username and password after importing them**

**We will not print out our url that contains our username and password**

Now that we have created our **CONNECTION STRING**, we can connect to SQL

#### Let's connect to the employees database and pull the first 5 rows

format: `pd.read_sql('literal sql syntax to pull query', connection_string)`

 - What do you notice about our current connection string?

In [ ]:
#url
url = f'mysql+pymysql://{env.user}:{env.password}@{env.host}/some_db'

In [ ]:
#update it 


In [ ]:
#connect to sql and pull query into df
pd.read_sql('select * from employees limit 5', url)

#### I like my sql querys formatted with line breaks

In [ ]:
pd.read_sql('''
select *
from employees
limit 5
''', url)

#### Let's make a bigger query:

- I want a dataframe with emp_no, first_name, last_name, and dept_name
- I want it only for women and their current department
- Only pull back the first 10 employees

In [ ]:
#query
    select emp_no, first_name, last_name, dept_name
    from employees
        join dept_emp
            using (emp_no)
        join departments
            using (dept_no)
    where gender = 'F'
    limit 10
    ;

In [ ]:
#connect to sql and pull query into df
pd.read_sql('''
    select emp_no, first_name, last_name, dept_name
    from employees
        join dept_emp
            using (emp_no)
        join departments
            using (dept_no)
    where gender = 'F'
    limit 10
    ;
    ''', url)

# Don't push your passwords!